esphome:
  name: iaq50w_bsec
  friendly_name: IAQ50w_bsec
  platformio_options:
  
    board_build.flash_mode: dout
    board_build.arduino.memory_type: opi_opi
    board_build.f_flash: 80000000L
  on_boot: 
    priority: 600
    then:
      - output.turn_on: ON_OFF_ADDON
      - output.turn_off: ADD
      - output.turn_off: CS
      - output.turn_off: INTERNAL_LED
      - output.turn_off: ON_OFF_ADDON
      - output.turn_off: ntc_vcc
      


esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  flash_size: 32MB
  framework:
    type: arduino
   
psram:
  mode: octal
  speed: 80MHz
  
# Enable logging
logger:
  hardware_uart: UART0
  level: VERBOSE
  baud_rate: 115200
  
# Enable Home Assistant API
api:
  encryption:
    key: "OsOJ9NbUD2z0IhBuvUJwc90JwBF6n3tzLG3jYv5RPjc="

ota:
  password: "e220fa7eb773f8c26b5446062826077f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Iaq50W Fallback Hotspot"
    password: "YcUEoIGu1MGx"

captive_portal:

web_server:
  port: 80
  
i2c:
  sda: 8
  scl: 9
  #frequency: 400kHz
  scan: true
  id: bus_a

output:
  - platform: gpio
    pin:
      number: 10
    id: "ON_OFF_ADDON"
  - platform: gpio
    pin:
      number: 18
    id: "ADD"
      
  - platform: gpio
    pin:
      number: 17
    id: "CS"
  - platform: gpio
    pin:
      number: 45
    id: "INTERNAL_LED"

  - platform: gpio
    pin:
      number: 1
    id: "ntc_vcc"




  - platform: ledc
    pin: GPIO04
    id: gpio_red
    frequency: "1000Hz"
    channel: 0
    inverted: true
    max_power: 80%
    
  - platform: ledc
    pin: GPIO05
    inverted: true
    id: gpio_green
    frequency: "1000Hz"
    channel: 1
    max_power: 80%

    
  - platform: ledc
    pin: GPIO06
    inverted: true
    id: gpio_blue
    frequency: "1000Hz"
    channel: 2
    max_power: 80%




light:

  - platform: rgb
    id: rgb_led
    name: "RGB LED"
    red: gpio_red
    green: gpio_green
    blue: gpio_blue

interval:
  - interval: 60s
    then:
      - output.turn_on: ntc_vcc
      - component.update: source_sensor
      - output.turn_off: ntc_vcc

sensor:
    
  - platform: ntc
    sensor: resistance_sensor
    calibration:
      b_constant: 3977
      reference_temperature: 25°C
      reference_resistance: 4.7kOhm
    name: NTC Temperature
  
  - platform: resistance
    id: resistance_sensor
    sensor: source_sensor
    configuration: UPSTREAM
    resistor: 4.7kOhm
    name: Resistance Sensor
    
  - platform: adc
    id: source_sensor
    pin: GPIO2
    attenuation: 11dB
    # Added:
    update_interval: never

  - platform: aht10
    variant: AHT10
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 60s