esphome:
  name: isoundv3
  friendly_name: IsoundV3
  on_boot:
    - priority: 600
      then:
        - switch.turn_off: addr
esp32:
  board: esp32dev
  framework:  
    type: arduino
    platform_version: "https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip"



# Specify the sources for external components
external_components:
  - source:
      type: git
      url: https://github.com/tv4you2016/external_components-esphome
    components: [ i2s_audio ]


psram:


# Example configuration entry
debug:
  update_interval: 1s

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "LvNU48bwzbsR7/IRIpLVWObts4a2kXAQxYljFhgLQrk="

ota:
  - platform: esphome
    password: "34d297f63eef9ea75b76892359dbd10e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Isound Fallback Hotspot"
    password: "nUrXchmz3Vuz"

web_server:
  port: 80
  
captive_portal:

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
  - platform: debug
    free:
      name: "Heap Free"

i2c:
  sda: GPIO33
  scl: GPIO32
  frequency: 400kHz

i2s_audio:
  - i2s_lrclk_pin: GPIO25
    i2s_bclk_pin: GPIO26
    i2s_mclk_pin: GPIO0




button:
  - platform: restart
    name: "Living Room Restart"

switch:
  - platform: gpio
    pin: GPIO14
    name: "6C/6D"
    id: addr
    restore_mode: ALWAYS_OFF


media_player:
  - platform: i2s_audio
    name: iSound
    id: iSound
    dac_type: external
    i2s_dout_pin: GPIO27
    mute_pin: 
      number: GPIO18
      inverted: true
    mode: stereo
    