esphome:
  libraries:
    - Networking
    - NetworkClientSecure

  name: isound
  friendly_name: Isound
  on_boot:
    - priority: 600
      then:
        - switch.turn_off: addr
esp32:
  board: esp32dev
  framework:
    type: arduino 

external_components:
  - source:
      type: git
      url: https://github.com/tv4you2016/external_components-esphome
    components: [ i2s_isound ]
    
  - source: github://pr#8604
    components: [ac_dimmer, async_tcp, captive_portal, esp32, esp32_rmt, esp32_rmt_led_strip, ethernet, heatpumpir, http_request, i2c, i2s_audio, ledc, logger, md5, neopixelbus, network, nextion, online_image, remote_base, remote_receiver, remote_transmitter, web_server_base, wifi]
    refresh: 1h
psram:

# Example configuration entry
debug:
  update_interval: 1s

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "LvNU48bwzbsR7/IRIpLVWObts4a2kXAQxYljFhgLQrk="

ota:
  - platform: esphome
    password: "34d297f63eef9ea75b76892359dbd10e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Isound Fallback Hotspot"
    password: "nUrXchmz3Vuz"

web_server:
  port: 80
  
captive_portal:

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
  - platform: debug
    free:
      name: "Heap Free"

i2c:
  sda: GPIO33
  scl: GPIO32
  frequency: 400kHz

i2s_isound:
  - i2s_lrclk_pin: GPIO25
    i2s_bclk_pin: GPIO26
    i2s_mclk_pin: GPIO0


button:
  - platform: restart
    name: "Living Room Restart"

switch:
  - platform: gpio
    pin: GPIO14
    name: "ADR"
    id: addr
    restore_mode: ALWAYS_OFF

 # - platform: gpio
 #   pin: 
 #     number: GPIO18
 #   id: MUTE
 #   name: "MUTE"
 #   inverted: true
 #   restore_mode: ALWAYS_OFF

media_player:
  - platform: i2s_isound
    name: iSound
    id: iSound
    dac_type: external
    i2s_dout_pin: GPIO27
    mute_pin: 
      number: GPIO18
      inverted: true
      #mode:
      #  output: true
      #  open_drain: true
    mode: stereo
    